``` python
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'test.test' doesn't exist")
[SQL: SELECT test.id AS test_id, test.name AS test_name 
FROM test]
``` 
